// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkd3dQVQHkg4qUR3NUQspKuzgLBuLza-M',
    appId: '1:299379216470:web:8ee5c2e07c229bfe87ebf7',
    messagingSenderId: '299379216470',
    projectId: 'aiot-tomato-leaf',
    authDomain: 'aiot-tomato-leaf.firebaseapp.com',
    storageBucket: 'aiot-tomato-leaf.firebasestorage.app',
    databaseURL: 'https://aiot-tomato-leaf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLx-awYFiXYc6z0aYmQonOa4vuzp-ty94',
    appId: '1:299379216470:android:2adc29014b1d958b87ebf7',
    messagingSenderId: '299379216470',
    projectId: 'aiot-tomato-leaf',
    storageBucket: 'aiot-tomato-leaf.firebasestorage.app',
    databaseURL: 'https://aiot-tomato-leaf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS3_1KkGq5wtJO6sY_lHmVPxip4dvIAPI',
    appId: '1:299379216470:ios:250b3082947ca06387ebf7',
    messagingSenderId: '299379216470',
    projectId: 'aiot-tomato-leaf',
    storageBucket: 'aiot-tomato-leaf.firebasestorage.app',
    iosBundleId: 'com.example.aiotTomato',
    databaseURL: 'https://aiot-tomato-leaf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS3_1KkGq5wtJO6sY_lHmVPxip4dvIAPI',
    appId: '1:299379216470:ios:250b3082947ca06387ebf7',
    messagingSenderId: '299379216470',
    projectId: 'aiot-tomato-leaf',
    storageBucket: 'aiot-tomato-leaf.firebasestorage.app',
    iosBundleId: 'com.example.aiotTomato',
    databaseURL: 'https://aiot-tomato-leaf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkd3dQVQHkg4qUR3NUQspKuzgLBuLza-M',
    appId: '1:299379216470:web:d3a93d60b498b15d87ebf7',
    messagingSenderId: '299379216470',
    projectId: 'aiot-tomato-leaf',
    authDomain: 'aiot-tomato-leaf.firebaseapp.com',
    storageBucket: 'aiot-tomato-leaf.firebasestorage.app',
    databaseURL: 'https://aiot-tomato-leaf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
